In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

from IPython.display import display
from itertools import compress

In [4]:
path = os.getcwd()+'/Data'
name = os.listdir(path)
name0 = []
for i in name:
    if i in ['ant','jedit','ivy','synapse']:
        sub_path = path+'/'+i
        for j in os.listdir(sub_path):
            print(j[:-4])
            name0.append(j[:-4])
for i in name:
    if i in ['lucene','velocity']:
        sub_path = path+'/'+i
        for j in os.listdir(sub_path):
            print(j[:-4])
            name0.append(j[:-4])
for i in name:
    if i in ['camel','log4j','xalan','xerces']:
        sub_path = path+'/'+i
        for j in os.listdir(sub_path):
            print(j[:-4])
            name0.append(j[:-4])
print(len(name0))

ant-1.3
ant-1.4
ant-1.5
ant-1.6
ant-1.7
ivy-1.1
ivy-1.4
ivy-2.0
jedit-3.2
jedit-4.0
jedit-4.1
jedit-4.2
jedit-4.3
synapse-1.0
synapse-1.1
synapse-1.2
lucene-2.0
lucene-2.2
lucene-2.4
velocity-1.4
velocity-1.5
velocity-1.6
camel-1.0
camel-1.2
camel-1.4
camel-1.6
log4j-1.0
log4j-1.1
xalan-2.4
xalan-2.5
xerces-1.3
xerces-1.4
32

In [5]:
for k in ['Bayes.csv', 'DescionTree.csv', 'Linear.csv']:
    temp = pd.read_csv(k)
    temp = temp.iloc[:,1:]
    result = result & ((temp['SMOTE&Bagging']>temp['SMOTE'])&(temp['SMOTE&Bagging']>temp['Bagging'])&(temp['SMOTE&Bagging']>temp['Normal']))
result = list(result)
for k in ['Bayes.csv', 'DescionTree.csv', 'Linear.csv']:
    temp = pd.read_csv(k)
    temp = temp.iloc[:,1:]
    result = ((temp['SMOTE&Bagging']>temp['SMOTE'])&(temp['SMOTE&Bagging']>temp['Bagging'])&(temp['SMOTE&Bagging']>temp['Normal']))
    result = list(result)
    print(list(compress(name0, result)))
list(compress(name0, result))

['ant-1.5', 'ant-1.6', 'ivy-1.4', 'jedit-3.2', 'synapse-1.1', 'lucene-2.0', 'camel-1.0', 'camel-1.2', 'camel-1.4', 'log4j-1.0', 'log4j-1.1', 'xalan-2.4']
['ant-1.3', 'ant-1.4', 'ant-1.5', 'ant-1.6', 'ant-1.7', 'ivy-2.0', 'jedit-3.2', 'jedit-4.0', 'jedit-4.1', 'jedit-4.2', 'synapse-1.0', 'synapse-1.2', 'lucene-2.0', 'velocity-1.4', 'velocity-1.6', 'camel-1.2', 'camel-1.4', 'camel-1.6', 'log4j-1.0', 'log4j-1.1', 'xalan-2.4', 'xalan-2.5', 'xerces-1.3', 'xerces-1.4']
['ant-1.5', 'ant-1.6', 'jedit-3.2', 'jedit-4.3', 'synapse-1.1', 'synapse-1.2', 'lucene-2.0', 'velocity-1.6', 'camel-1.0', 'log4j-1.0', 'xalan-2.4', 'xerces-1.3']

In [13]:
for k in ['Bayes.csv', 'DescionTree.csv', 'Linear.csv']:
    temp = pd.read_csv(k)
    temp = temp.iloc[:,1:]
    result = ((temp['SMOTE&Bagging']>temp['SMOTE'])&(temp['SMOTE&Bagging']>temp['Bagging'])&(temp['SMOTE&Bagging']>temp['Normal']))
    temp = temp[result]
    temp['SMOTE'] = (temp['SMOTE&Bagging']-temp['SMOTE'])/temp['SMOTE&Bagging']
    temp['Bagging'] = (temp['SMOTE&Bagging']-temp['Bagging'])/temp['SMOTE&Bagging']
    temp['Normal'] = (temp['SMOTE&Bagging']-temp['Normal'])/temp['SMOTE&Bagging']
    display(temp)
    print(temp['SMOTE'].mean())
    print(temp['Bagging'].mean())
    print(temp['Normal'].mean())
#     display(temp[result])

    SMOTE&Bagging     SMOTE   Bagging    Normal
2         0.58137  0.135852  0.001858  0.135852
3         0.79079  0.046144  0.002921  0.046144
6         0.41512  0.098718  0.005324  0.098718
8         0.84095  0.013532  0.006005  0.013532
14        0.68693  0.036714  0.004848  0.036714
16        0.76362  0.020298  0.001716  0.020298
22        0.59756  0.055727  0.003012  0.055727
23        0.64878  0.051589  0.011868  0.051589
24        0.69307  0.165236  0.011788  0.165236
26        0.73345  0.054128  0.004949  0.054128
27        0.78342  0.008820  0.000396  0.008820
28        0.65522  0.136366  0.007936  0.136366

0.0685936831086394
0.005218403674873623
0.0685936831086394

    SMOTE&Bagging     SMOTE   Bagging    Normal
0         0.64916  0.202431  0.132155  0.173948
1         0.63082  0.075854  0.052138  0.080023
2         0.64938  0.052342  0.046798  0.058363
3         0.77234  0.010578  0.086529  0.036137
4         0.77376  0.046500  0.078590  0.058881
7         0.66823  0.102165  0.067836  0.105114
8         0.82847  0.201468  0.104433  0.214721
9         0.81060  0.056378  0.054626  0.068110
10        0.77806  0.029034  0.080842  0.060304
11        0.78986  0.057010  0.059162  0.066341
13        0.68523  0.042453  0.046437  0.006421
15        0.68317  0.038102  0.035189  0.037780
16        0.72853  0.028002  0.029306  0.025243
19        0.60323  0.001923  0.011389  0.016279
21        0.75180  0.034052  0.060122  0.052820
23        0.68329  0.066004  0.092918  0.082835
24        0.72425  0.196479  0.107132  0.184550
25        0.72063  0.072825  0.089352  0.101966
26        0.70587  0.115149  0.042727  0.099820
27        0.76137  0.066052  0.035791  0.052891
28        0.69903  0.074003  0.072014  0.075762
29        0.62022  0.030844  0.041469  0.052030
30        0.78947  0.029716  0.048653  0.090124
31        0.74388  0.001371  0.012542  0.011776

0.0679472490627899
0.062006378364667235
0.07550991840152241

    SMOTE&Bagging     SMOTE   Bagging    Normal
2         0.56306  0.108443  0.000018  0.108443
3         0.76046  0.030758  0.001525  0.030758
8         0.84222  0.000784  0.000511  0.000784
12        0.64499  0.010248  0.000403  0.010248
14        0.68691  0.000189  0.004236  0.000189
15        0.69651  0.040129  0.018392  0.040129
16        0.74108  0.000148  0.004332  0.000148
21        0.67281  0.031525  0.003745  0.031525
22        0.59912  0.058185  0.012251  0.058185
26        0.75768  0.029894  0.001518  0.029894
28        0.66765  0.219636  0.015532  0.219636
30        0.78328  0.108850  0.019610  0.108850

0.05323239733102097
0.0068394086824690075
0.05323239733102097

In [14]:
for k in ['Bayes.csv', 'DescionTree.csv', 'Linear.csv']:
    temp = pd.read_csv(k)
    temp = temp.iloc[:,1:]
    result = result & ((temp['SMOTE&Bagging']>temp['SMOTE'])&(temp['SMOTE&Bagging']>temp['Bagging'])&(temp['SMOTE&Bagging']>temp['Normal']))

for k in ['Bayes.csv', 'DescionTree.csv', 'Linear.csv']:
    temp = pd.read_csv(k)
    temp = temp.iloc[:,1:]
    temp = temp[result]
    temp['SMOTE'] = (temp['SMOTE&Bagging']-temp['SMOTE'])/temp['SMOTE&Bagging']
    temp['Bagging'] = (temp['SMOTE&Bagging']-temp['Bagging'])/temp['SMOTE&Bagging']
    temp['Normal'] = (temp['SMOTE&Bagging']-temp['Normal'])/temp['SMOTE&Bagging']
    display(temp)
    print(temp['SMOTE'].mean())
    print(temp['Bagging'].mean())
    print(temp['Normal'].mean())
#     display(temp[result])

    SMOTE&Bagging     SMOTE   Bagging    Normal
2         0.58137  0.135852  0.001858  0.135852
3         0.79079  0.046144  0.002921  0.046144
8         0.84095  0.013532  0.006005  0.013532
16        0.76362  0.020298  0.001716  0.020298
26        0.73345  0.054128  0.004949  0.054128
28        0.65522  0.136366  0.007936  0.136366

0.06771996419154118
0.004230819170257882
0.06771996419154118

    SMOTE&Bagging     SMOTE   Bagging    Normal
2         0.64938  0.052342  0.046798  0.058363
3         0.77234  0.010578  0.086529  0.036137
8         0.82847  0.201468  0.104433  0.214721
16        0.72853  0.028002  0.029306  0.025243
26        0.70587  0.115149  0.042727  0.099820
28        0.69903  0.074003  0.072014  0.075762

0.08025684385954036
0.06363471437467559
0.08500770473964549

    SMOTE&Bagging     SMOTE   Bagging    Normal
2         0.56306  0.108443  0.000018  0.108443
3         0.76046  0.030758  0.001525  0.030758
8         0.84222  0.000784  0.000511  0.000784
16        0.74108  0.000148  0.004332  0.000148
26        0.75768  0.029894  0.001518  0.029894
28        0.66765  0.219636  0.015532  0.219636

0.06494380798526851
0.003905850923925133
0.06494380798526851